# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      project: ENV['IOS_PROJECT_PATH'],
      scheme: ENV['IOS_SCHEME']
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    update_app_identifier(
      xcodeproj: ENV['IOS_PROJECT_PATH'],
      plist_path: ENV['IOS_PLIST_PATH'],
      app_identifier: ENV['IOS_APP_ID']
    )

    increment_version_number(
      xcodeproj: ENV['IOS_PROJECT_PATH'],
      version_number: File.open(
        "#{ENV['BITRISE_SOURCE_DIR']}/VERSION/iOS", 'r'
      ).read.strip
    )

    match(
      git_branch: "cockpit/abctotaal",
    )

    gym(
      project: ENV['IOS_PROJECT_PATH'],
      configuration: 'Release',
      scheme: ENV['IOS_SCHEME'],
      codesigning_identity: ENV['IOS_CODESIGNING_ID'],
      clean: true,
      output_name: 'debug.ipa',
      output_directory: ENV['IOS_BUILD_DIR'],
      buildlog_path: ENV['IOS_BUILD_DIR']
    ) # Build your app - more options available
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  lane :screenshot do
    snapshot(
      scheme: 'WinAdmCockpitUISnapshotTests2',
      ios_version: '9.3',
      localize_simulator: true,
      reinstall_app: true,
      number_of_retries: 5,
      erase_simulator: true,
      configuration: 'Debug',
      buildlog_path: ENV['IOS_SCREENSHOTS_DIR'],
      output_directory: ENV['IOS_SCREENSHOTS_DIR']
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    update_app_identifier(
      app_identifier: ENV['IOS_APP_ID']
    )

    gym(
      project: ENV['IOS_PROJECT_PATH'],
      configuration: 'Release',
      scheme: ENV['IOS_SCHEME'],
      codesigning_identity: ENV['IOS_CODESIGNING_ID'],
      clean: true,
      output_name: 'release.ipa',
      output_directory: 'ios/build',
      buildlog_path: ENV['IOS_BUILD_DIR']
    ) # Build your app - more options available
    #deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

#  slack not configured
# after_all do |lane|
#    # This block is called, only if the executed lane was successful
#
#    slack(
#      message: ":fastlane: #{lane} build succeeded"
#    )
#  end

#  error do |lane, e|
#    slack(
#      message: ":fastlane: #{lane} failed because:\n\r`#{e.message}`",
#      success: false
#    )
#  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
